function
require(m,r)package=package
or{loaded={}}if
package.loaded[m]then
return
package.loaded[m]end
if
m=="common"then
r=(function()return{a=42}end)()end
package.loaded[m]=package.loaded[m]or
r
or
true
return
package.loaded[m]end
local
a,b=require("common"),require("common")print(a.a,b.a)